# render.yaml
services:
  - type: web
    name: journey-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DUFFEL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: static
    name: journey-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://journey-backend.onrender.com